import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { UnifrakturCook as UnifrakturCookLoader } from "next/font/google"; 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const unifra = UnifrakturCookLoader({
  weight: "700", 
  subsets: ["latin"],
  variable: "--font-unifrakturcook",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.4.2/css/all.css" />
      </head>
      <body
        className={`${unifra.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
